import { locations as sriLankaCities } from "./locations";

export type Continent =
  | "South Asia"
  | "Southeast Asia"
  | "Middle East"
  | "Africa"
  | "Europe"
  | "North America"
  | "Latin America & Caribbean"
  | "Oceania";

export type Region = {
  slug: string;
  name: string;
  /** Main cities and towns, used in copy and keywords. */
  cities: string[];
  /** Optional local sentence; a generic one is built when missing. */
  note?: string;
  /** Industry slugs most common locally (see lib/industries.ts). */
  focus?: string[];
};

export type Country = {
  slug: string;
  name: string;
  continent: Continent;
  /** ISO 3166-1 alpha-2, used in structured data. */
  code: string;
  currency: string;
  currencySymbol: string;
  /** Local name of the sales tax, e.g. VAT, GST, sales tax. */
  tax: string;
  /** Popular non-cash payment methods, recorded in MariaPoS as card or transfer with a reference. */
  payments: string[];
  /** Largest commercial cities. */
  cities: string[];
  /** One sentence about local retail that opens the country page. */
  note: string;
  focus: string[];
  /** What a region is called locally: state, province, division… */
  regionLabel?: string;
  regions?: Region[];
};

export const slugify = (text: string) =>
  text
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

/** Builds regions from compact [name, cities] tuples. */
const r = (rows: [name: string, cities: string[]][]): Region[] =>
  rows.map(([name, cities]) => ({ slug: slugify(name), name, cities }));

const retail = ["supermarket-grocery", "pharmacy", "hardware-store", "clothing-textile"];
const trade = ["supermarket-grocery", "wholesale-distribution", "pharmacy", "electronics-mobile"];

export const countries: Country[] = [
  // ───────────── South Asia ─────────────
  {
    slug: "sri-lanka",
    name: "Sri Lanka",
    continent: "South Asia",
    code: "LK",
    currency: "LKR",
    currencySymbol: "Rs.",
    tax: "VAT and SSCL",
    payments: ["LANKAQR", "bank transfers", "cheques"],
    cities: ["Colombo", "Kandy", "Galle", "Jaffna", "Kurunegala", "Negombo"],
    note: "MariaPoS is built in Colombo, so it already fits Sri Lankan counters: post-dated supplier cheques, customer credit books and billing that keeps going when the internet or power drops.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store", "wholesale-distribution"],
    regionLabel: "city",
    regions: sriLankaCities.map((l) => ({
      slug: l.slug,
      name: l.name,
      cities: [l.name, ...l.nearby],
      note: `${l.note} ${l.name} is in ${l.district} District, ${l.province} Province.`,
      focus: l.focus,
    })),
  },
  {
    slug: "india",
    name: "India",
    continent: "South Asia",
    code: "IN",
    currency: "INR",
    currencySymbol: "₹",
    tax: "GST",
    payments: ["UPI", "RuPay cards", "bank transfers"],
    cities: ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Hyderabad", "Kolkata", "Pune", "Ahmedabad"],
    note: "From kirana stores to medical shops and wholesale markets, Indian retailers need GST-ready billing, loose-item weighing and strict control of credit (udhaar) customers.",
    focus: ["supermarket-grocery", "pharmacy", "wholesale-distribution", "clothing-textile"],
    regionLabel: "state",
    regions: r([
      ["Maharashtra", ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad"]],
      ["Delhi", ["New Delhi", "Dwarka", "Rohini", "Karol Bagh", "Chandni Chowk"]],
      ["Karnataka", ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"]],
      ["Tamil Nadu", ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"]],
      ["Telangana", ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad"]],
      ["West Bengal", ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"]],
      ["Gujarat", ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"]],
      ["Uttar Pradesh", ["Lucknow", "Kanpur", "Noida", "Ghaziabad", "Agra", "Varanasi"]],
      ["Rajasthan", ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer"]],
      ["Kerala", ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur", "Kannur"]],
      ["Andhra Pradesh", ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Nellore"]],
      ["Madhya Pradesh", ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain"]],
      ["Punjab", ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Mohali"]],
      ["Haryana", ["Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal"]],
      ["Bihar", ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur"]],
      ["Odisha", ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur"]],
      ["Assam", ["Guwahati", "Silchar", "Dibrugarh", "Jorhat"]],
      ["Jharkhand", ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"]],
      ["Chhattisgarh", ["Raipur", "Bhilai", "Bilaspur", "Korba"]],
      ["Uttarakhand", ["Dehradun", "Haridwar", "Haldwani", "Rishikesh"]],
      ["Goa", ["Panaji", "Margao", "Vasco da Gama", "Mapusa"]],
      ["Himachal Pradesh", ["Shimla", "Dharamshala", "Mandi", "Solan"]],
      ["Jammu and Kashmir", ["Srinagar", "Jammu", "Anantnag", "Baramulla"]],
    ]),
  },
  {
    slug: "bangladesh",
    name: "Bangladesh",
    continent: "South Asia",
    code: "BD",
    currency: "BDT",
    currencySymbol: "৳",
    tax: "VAT",
    payments: ["bKash", "Nagad", "Rocket", "bank transfers"],
    cities: ["Dhaka", "Chattogram", "Khulna", "Rajshahi", "Sylhet", "Gazipur", "Narayanganj"],
    note: "Bangladeshi shops, super shops and pharmacies handle huge daily volumes, mobile-wallet payments and frequent power cuts, which is exactly where an offline-first POS pays off.",
    focus: ["supermarket-grocery", "pharmacy", "clothing-textile", "wholesale-distribution"],
    regionLabel: "division",
    regions: r([
      ["Dhaka", ["Dhaka", "Gazipur", "Narayanganj", "Savar", "Tangail", "Narsingdi"]],
      ["Chattogram", ["Chattogram", "Cox's Bazar", "Cumilla", "Feni", "Noakhali", "Brahmanbaria"]],
      ["Khulna", ["Khulna", "Jessore", "Kushtia", "Satkhira", "Bagerhat"]],
      ["Rajshahi", ["Rajshahi", "Bogura", "Pabna", "Sirajganj", "Naogaon"]],
      ["Sylhet", ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"]],
      ["Barishal", ["Barishal", "Patuakhali", "Bhola", "Pirojpur"]],
      ["Rangpur", ["Rangpur", "Dinajpur", "Saidpur", "Kurigram", "Thakurgaon"]],
      ["Mymensingh", ["Mymensingh", "Jamalpur", "Netrokona", "Sherpur"]],
    ]),
  },
  {
    slug: "pakistan",
    name: "Pakistan",
    continent: "South Asia",
    code: "PK",
    currency: "PKR",
    currencySymbol: "Rs",
    tax: "sales tax (GST)",
    payments: ["JazzCash", "Easypaisa", "Raast", "bank transfers"],
    cities: ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Multan", "Peshawar"],
    note: "Pakistani general stores, marts and medical stores run on thin margins and trade credit, so accurate stock, supplier ledgers and cash control matter at every counter.",
    focus: trade,
    regionLabel: "province",
    regions: r([
      ["Punjab", ["Lahore", "Faisalabad", "Rawalpindi", "Multan", "Gujranwala", "Sialkot"]],
      ["Sindh", ["Karachi", "Hyderabad", "Sukkur", "Larkana", "Nawabshah"]],
      ["Khyber Pakhtunkhwa", ["Peshawar", "Mardan", "Abbottabad", "Swat", "Kohat"]],
      ["Balochistan", ["Quetta", "Gwadar", "Turbat", "Khuzdar"]],
      ["Islamabad Capital Territory", ["Islamabad", "Blue Area", "F-10", "G-9"]],
    ]),
  },
  {
    slug: "nepal",
    name: "Nepal",
    continent: "South Asia",
    code: "NP",
    currency: "NPR",
    currencySymbol: "Rs",
    tax: "VAT",
    payments: ["eSewa", "Khalti", "Fonepay QR", "bank transfers"],
    cities: ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur", "Birgunj", "Butwal"],
    note: "Nepal's departmental stores, pharmacies and hardware shops need billing that works through unreliable connectivity and records QR wallet payments clearly.",
    focus: retail,
  },
  {
    slug: "maldives",
    name: "Maldives",
    continent: "South Asia",
    code: "MV",
    currency: "MVR",
    currencySymbol: "MVR",
    tax: "GST",
    payments: ["BML transfers", "cards"],
    cities: ["Malé", "Hulhumalé", "Addu City", "Fuvahmulah", "Kulhudhuffushi"],
    note: "Island shops in the Maldives depend on imported stock with changing landed costs, and FIFO batch costing keeps margins accurate.",
    focus: ["supermarket-grocery", "hardware-store", "bakery-cafe"],
  },
  {
    slug: "bhutan",
    name: "Bhutan",
    continent: "South Asia",
    code: "BT",
    currency: "BTN",
    currencySymbol: "Nu.",
    tax: "GST",
    payments: ["mBoB", "mPay", "bank transfers"],
    cities: ["Thimphu", "Phuntsholing", "Paro", "Gelephu"],
    note: "Bhutanese retailers in Thimphu and Phuntsholing need a simple, reliable POS that keeps billing through connectivity gaps in the mountains.",
    focus: ["supermarket-grocery", "hardware-store"],
  },

  // ───────────── Southeast Asia ─────────────
  {
    slug: "malaysia",
    name: "Malaysia",
    continent: "Southeast Asia",
    code: "MY",
    currency: "MYR",
    currencySymbol: "RM",
    tax: "SST",
    payments: ["DuitNow QR", "Touch 'n Go eWallet", "cards"],
    cities: ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Kota Kinabalu", "Kuching"],
    note: "Malaysian mini markets, kedai runcit and pharmacies need fast checkout, QR payments and SST-ready reports.",
    focus: retail,
    regionLabel: "state",
    regions: r([
      ["Kuala Lumpur", ["Kuala Lumpur", "Bukit Bintang", "Cheras", "Kepong", "Bangsar"]],
      ["Selangor", ["Shah Alam", "Petaling Jaya", "Subang Jaya", "Klang", "Kajang"]],
      ["Johor", ["Johor Bahru", "Batu Pahat", "Muar", "Kluang"]],
      ["Penang", ["George Town", "Butterworth", "Bukit Mertajam", "Bayan Lepas"]],
      ["Perak", ["Ipoh", "Taiping", "Teluk Intan", "Sitiawan"]],
      ["Sabah", ["Kota Kinabalu", "Sandakan", "Tawau", "Lahad Datu"]],
      ["Sarawak", ["Kuching", "Miri", "Sibu", "Bintulu"]],
      ["Kedah", ["Alor Setar", "Sungai Petani", "Kulim", "Langkawi"]],
      ["Kelantan", ["Kota Bharu", "Pasir Mas", "Tanah Merah"]],
      ["Pahang", ["Kuantan", "Temerloh", "Bentong", "Raub"]],
      ["Negeri Sembilan", ["Seremban", "Nilai", "Port Dickson"]],
      ["Melaka", ["Melaka City", "Alor Gajah", "Jasin"]],
      ["Terengganu", ["Kuala Terengganu", "Kemaman", "Dungun"]],
    ]),
  },
  {
    slug: "singapore",
    name: "Singapore",
    continent: "Southeast Asia",
    code: "SG",
    currency: "SGD",
    currencySymbol: "S$",
    tax: "GST",
    payments: ["PayNow", "NETS", "cards"],
    cities: ["Jurong", "Tampines", "Woodlands", "Ang Mo Kio", "Bedok", "Orchard", "Little India"],
    note: "Singapore's neighbourhood minimarts, provision shops and pharmacies compete on speed, so every second at checkout counts.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile", "cosmetics-beauty"],
  },
  {
    slug: "indonesia",
    name: "Indonesia",
    continent: "Southeast Asia",
    code: "ID",
    currency: "IDR",
    currencySymbol: "Rp",
    tax: "PPN (VAT)",
    payments: ["QRIS", "GoPay", "OVO", "DANA", "bank transfers"],
    cities: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar", "Denpasar"],
    note: "Indonesian toko, minimarkets and apotek handle high volumes of small transactions and QRIS payments across thousands of islands.",
    focus: retail,
    regionLabel: "province",
    regions: r([
      ["Jakarta", ["Central Jakarta", "South Jakarta", "West Jakarta", "East Jakarta", "North Jakarta"]],
      ["West Java", ["Bandung", "Bekasi", "Bogor", "Depok", "Cirebon"]],
      ["East Java", ["Surabaya", "Malang", "Sidoarjo", "Kediri"]],
      ["Central Java", ["Semarang", "Solo", "Tegal", "Pekalongan"]],
      ["Bali", ["Denpasar", "Badung", "Gianyar", "Ubud"]],
      ["North Sumatra", ["Medan", "Binjai", "Pematangsiantar"]],
      ["Banten", ["Tangerang", "Serang", "Cilegon", "South Tangerang"]],
      ["South Sulawesi", ["Makassar", "Parepare", "Palopo"]],
    ]),
  },
  {
    slug: "philippines",
    name: "Philippines",
    continent: "Southeast Asia",
    code: "PH",
    currency: "PHP",
    currencySymbol: "₱",
    tax: "VAT",
    payments: ["GCash", "Maya", "InstaPay transfers", "cards"],
    cities: ["Manila", "Quezon City", "Cebu City", "Davao City", "Makati", "Pasig", "Iloilo City"],
    note: "Filipino groceries, sari-sari wholesalers and drugstores need quick billing, GCash payment records and credit tracking for suki customers.",
    focus: trade,
    regionLabel: "region",
    regions: r([
      ["Metro Manila", ["Manila", "Quezon City", "Makati", "Pasig", "Taguig", "Caloocan"]],
      ["Central Visayas", ["Cebu City", "Mandaue", "Lapu-Lapu", "Tagbilaran", "Dumaguete"]],
      ["Davao Region", ["Davao City", "Tagum", "Panabo", "Digos"]],
      ["Calabarzon", ["Antipolo", "Calamba", "Batangas City", "Dasmariñas", "Lucena"]],
      ["Central Luzon", ["Angeles", "San Fernando", "Olongapo", "Malolos", "Cabanatuan"]],
      ["Western Visayas", ["Iloilo City", "Bacolod", "Roxas City", "Kalibo"]],
      ["Northern Mindanao", ["Cagayan de Oro", "Iligan", "Valencia", "Malaybalay"]],
    ]),
  },
  {
    slug: "thailand",
    name: "Thailand",
    continent: "Southeast Asia",
    code: "TH",
    currency: "THB",
    currencySymbol: "฿",
    tax: "VAT",
    payments: ["PromptPay QR", "TrueMoney", "cards"],
    cities: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Khon Kaen", "Hat Yai", "Nakhon Ratchasima"],
    note: "Thai minimarts, pharmacies and tourist shops take PromptPay all day and need clean, reconciled payment reports.",
    focus: ["supermarket-grocery", "pharmacy", "cosmetics-beauty", "bakery-cafe"],
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    continent: "Southeast Asia",
    code: "VN",
    currency: "VND",
    currencySymbol: "₫",
    tax: "VAT",
    payments: ["VietQR", "MoMo", "ZaloPay", "bank transfers"],
    cities: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Nha Trang"],
    note: "Vietnamese convenience stores, pharmacies and phone shops take QR bank transfers constantly and need every payment matched to a bill.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile", "clothing-textile"],
  },
  {
    slug: "cambodia",
    name: "Cambodia",
    continent: "Southeast Asia",
    code: "KH",
    currency: "KHR / USD",
    currencySymbol: "$",
    tax: "VAT",
    payments: ["KHQR", "ABA Pay", "Wing"],
    cities: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham"],
    note: "Cambodian marts and shops deal in both riel and US dollars, with KHQR payments on almost every bill.",
    focus: ["supermarket-grocery", "electronics-mobile", "cosmetics-beauty"],
  },
  {
    slug: "myanmar",
    name: "Myanmar",
    continent: "Southeast Asia",
    code: "MM",
    currency: "MMK",
    currencySymbol: "K",
    tax: "commercial tax",
    payments: ["KBZPay", "Wave Money", "AYA Pay"],
    cities: ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Taunggyi"],
    note: "Shops in Yangon and Mandalay need a POS that keeps working through power and internet interruptions.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile"],
  },

  // ───────────── Middle East ─────────────
  {
    slug: "united-arab-emirates",
    name: "United Arab Emirates",
    continent: "Middle East",
    code: "AE",
    currency: "AED",
    currencySymbol: "AED",
    tax: "VAT",
    payments: ["cards", "Apple Pay", "bank transfers"],
    cities: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain", "Ras Al Khaimah"],
    note: "UAE groceries, cafeterias and trading companies run long hours with multiple cashiers, VAT-ready reporting and heavy supplier credit.",
    focus: ["supermarket-grocery", "wholesale-distribution", "electronics-mobile", "bakery-cafe"],
    regionLabel: "emirate",
    regions: r([
      ["Dubai", ["Deira", "Bur Dubai", "Al Quoz", "Jumeirah", "Al Barsha", "Karama"]],
      ["Abu Dhabi", ["Abu Dhabi City", "Al Ain", "Mussafah", "Khalifa City"]],
      ["Sharjah", ["Sharjah City", "Al Nahda", "Industrial Area", "Khor Fakkan"]],
      ["Ajman", ["Ajman City", "Al Jurf", "Al Nuaimiya"]],
      ["Ras Al Khaimah", ["RAK City", "Al Nakheel", "Al Hamra"]],
      ["Fujairah", ["Fujairah City", "Dibba", "Masafi"]],
      ["Umm Al Quwain", ["Umm Al Quwain City", "Al Salama"]],
    ]),
  },
  {
    slug: "saudi-arabia",
    name: "Saudi Arabia",
    continent: "Middle East",
    code: "SA",
    currency: "SAR",
    currencySymbol: "SAR",
    tax: "VAT",
    payments: ["mada", "STC Pay", "cards"],
    cities: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Taif"],
    note: "Saudi baqalas, supermarkets and pharmacies need VAT-ready billing, mada card payments and close control of cashier shifts.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile", "bakery-cafe"],
    regionLabel: "region",
    regions: r([
      ["Riyadh Province", ["Riyadh", "Al Kharj", "Al Majmaah", "Diriyah"]],
      ["Makkah Province", ["Jeddah", "Mecca", "Taif", "Rabigh"]],
      ["Eastern Province", ["Dammam", "Khobar", "Dhahran", "Jubail", "Al Ahsa"]],
      ["Madinah Province", ["Medina", "Yanbu", "Al Ula"]],
      ["Asir Province", ["Abha", "Khamis Mushait", "Bisha"]],
      ["Qassim Province", ["Buraidah", "Unaizah", "Ar Rass"]],
    ]),
  },
  {
    slug: "qatar",
    name: "Qatar",
    continent: "Middle East",
    code: "QA",
    currency: "QAR",
    currencySymbol: "QAR",
    tax: "applicable taxes",
    payments: ["cards", "bank transfers"],
    cities: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Lusail"],
    note: "Qatar's groceries, cafeterias and trading shops serve a busy, diverse customer base across long opening hours.",
    focus: ["supermarket-grocery", "bakery-cafe", "electronics-mobile"],
  },
  {
    slug: "kuwait",
    name: "Kuwait",
    continent: "Middle East",
    code: "KW",
    currency: "KWD",
    currencySymbol: "KD",
    tax: "applicable taxes",
    payments: ["KNET", "cards"],
    cities: ["Kuwait City", "Hawalli", "Salmiya", "Farwaniya", "Jahra", "Fahaheel"],
    note: "Kuwaiti co-op suppliers, groceries and phone shops need fast billing and clear records of KNET card payments.",
    focus: ["supermarket-grocery", "electronics-mobile", "wholesale-distribution"],
  },
  {
    slug: "oman",
    name: "Oman",
    continent: "Middle East",
    code: "OM",
    currency: "OMR",
    currencySymbol: "OMR",
    tax: "VAT",
    payments: ["cards", "bank transfers"],
    cities: ["Muscat", "Seeb", "Salalah", "Sohar", "Nizwa", "Sur"],
    note: "Omani trading shops and supermarkets need VAT-ready bills and reliable stock control across branches.",
    focus: ["supermarket-grocery", "hardware-store", "wholesale-distribution"],
  },
  {
    slug: "bahrain",
    name: "Bahrain",
    continent: "Middle East",
    code: "BH",
    currency: "BHD",
    currencySymbol: "BD",
    tax: "VAT",
    payments: ["BenefitPay", "cards"],
    cities: ["Manama", "Muharraq", "Riffa", "Hamad Town", "Isa Town"],
    note: "Bahraini cold stores, groceries and cafeterias need fast, VAT-ready billing with BenefitPay payments recorded.",
    focus: ["supermarket-grocery", "bakery-cafe", "electronics-mobile"],
  },
  {
    slug: "jordan",
    name: "Jordan",
    continent: "Middle East",
    code: "JO",
    currency: "JOD",
    currencySymbol: "JD",
    tax: "general sales tax",
    payments: ["CliQ", "cards"],
    cities: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba"],
    note: "Jordanian supermarkets, pharmacies and clothing stores need tight stock control and reliable sales-tax reporting.",
    focus: retail,
  },

  // ───────────── Africa ─────────────
  {
    slug: "nigeria",
    name: "Nigeria",
    continent: "Africa",
    code: "NG",
    currency: "NGN",
    currencySymbol: "₦",
    tax: "VAT",
    payments: ["bank transfers", "POS card terminals", "USSD"],
    cities: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Enugu"],
    note: "Nigerian supermarkets, pharmacies and wholesalers take many payments by bank transfer and deal with frequent power and network outages.",
    focus: trade,
    regionLabel: "state",
    regions: r([
      ["Lagos", ["Ikeja", "Lekki", "Surulere", "Yaba", "Ikorodu", "Victoria Island"]],
      ["Federal Capital Territory", ["Abuja", "Garki", "Wuse", "Maitama", "Kubwa"]],
      ["Kano", ["Kano", "Wudil", "Gaya"]],
      ["Rivers", ["Port Harcourt", "Obio-Akpor", "Bonny"]],
      ["Oyo", ["Ibadan", "Ogbomosho", "Oyo"]],
      ["Kaduna", ["Kaduna", "Zaria", "Kafanchan"]],
      ["Enugu", ["Enugu", "Nsukka", "Awgu"]],
      ["Anambra", ["Onitsha", "Awka", "Nnewi"]],
      ["Edo", ["Benin City", "Auchi", "Ekpoma"]],
    ]),
  },
  {
    slug: "kenya",
    name: "Kenya",
    continent: "Africa",
    code: "KE",
    currency: "KES",
    currencySymbol: "KSh",
    tax: "VAT",
    payments: ["M-Pesa", "Airtel Money", "cards"],
    cities: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika"],
    note: "Kenyan shops, chemists and hardware stores take M-Pesa on most sales, so every payment needs a reference matched to the bill.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store", "electronics-mobile"],
    regionLabel: "county",
    regions: r([
      ["Nairobi", ["Nairobi CBD", "Westlands", "Eastleigh", "Karen", "Kasarani"]],
      ["Mombasa", ["Mombasa", "Nyali", "Likoni", "Bamburi"]],
      ["Kisumu", ["Kisumu", "Maseno", "Ahero"]],
      ["Nakuru", ["Nakuru", "Naivasha", "Molo"]],
      ["Kiambu", ["Thika", "Ruiru", "Kiambu", "Limuru"]],
      ["Uasin Gishu", ["Eldoret", "Burnt Forest", "Turbo"]],
    ]),
  },
  {
    slug: "south-africa",
    name: "South Africa",
    continent: "Africa",
    code: "ZA",
    currency: "ZAR",
    currencySymbol: "R",
    tax: "VAT",
    payments: ["cards", "EFT", "SnapScan", "Zapper"],
    cities: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Gqeberha", "Bloemfontein"],
    note: "South African spaza shops, pharmacies and hardware stores need POS that survives load-shedding, and offline-first billing does exactly that.",
    focus: ["supermarket-grocery", "hardware-store", "pharmacy", "clothing-textile"],
    regionLabel: "province",
    regions: r([
      ["Gauteng", ["Johannesburg", "Pretoria", "Soweto", "Sandton", "Midrand"]],
      ["Western Cape", ["Cape Town", "Stellenbosch", "George", "Paarl"]],
      ["KwaZulu-Natal", ["Durban", "Pietermaritzburg", "Richards Bay", "Newcastle"]],
      ["Eastern Cape", ["Gqeberha", "East London", "Mthatha"]],
      ["Free State", ["Bloemfontein", "Welkom", "Bethlehem"]],
      ["Limpopo", ["Polokwane", "Tzaneen", "Thohoyandou"]],
      ["Mpumalanga", ["Mbombela", "Witbank", "Secunda"]],
      ["North West", ["Rustenburg", "Mahikeng", "Klerksdorp"]],
      ["Northern Cape", ["Kimberley", "Upington", "Springbok"]],
    ]),
  },
  {
    slug: "ghana",
    name: "Ghana",
    continent: "Africa",
    code: "GH",
    currency: "GHS",
    currencySymbol: "GH₵",
    tax: "VAT",
    payments: ["MTN MoMo", "Telecel Cash", "cards"],
    cities: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast", "Tema"],
    note: "Ghanaian provision stores, pharmacies and wholesalers take mobile money constantly and need it reconciled with cash every day.",
    focus: trade,
  },
  {
    slug: "tanzania",
    name: "Tanzania",
    continent: "Africa",
    code: "TZ",
    currency: "TZS",
    currencySymbol: "TSh",
    tax: "VAT",
    payments: ["M-Pesa", "Tigo Pesa", "Airtel Money"],
    cities: ["Dar es Salaam", "Arusha", "Mwanza", "Dodoma", "Zanzibar City", "Mbeya"],
    note: "Tanzanian dukas, pharmacies and hardware shops rely on mobile money and need billing that keeps working offline.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store"],
  },
  {
    slug: "uganda",
    name: "Uganda",
    continent: "Africa",
    code: "UG",
    currency: "UGX",
    currencySymbol: "USh",
    tax: "VAT",
    payments: ["MTN MoMo", "Airtel Money"],
    cities: ["Kampala", "Entebbe", "Jinja", "Mbarara", "Gulu", "Mbale"],
    note: "Ugandan supermarkets and wholesale shops handle mobile money, bulk sales and credit customers side by side.",
    focus: trade,
  },
  {
    slug: "egypt",
    name: "Egypt",
    continent: "Africa",
    code: "EG",
    currency: "EGP",
    currencySymbol: "E£",
    tax: "VAT",
    payments: ["InstaPay", "Fawry", "Meeza cards"],
    cities: ["Cairo", "Alexandria", "Giza", "Mansoura", "Tanta", "Port Said"],
    note: "Egyptian supermarkets, pharmacies and clothing stores need accurate VAT, fast billing and tight stock control.",
    focus: retail,
  },
  {
    slug: "ethiopia",
    name: "Ethiopia",
    continent: "Africa",
    code: "ET",
    currency: "ETB",
    currencySymbol: "Br",
    tax: "VAT",
    payments: ["telebirr", "CBE Birr", "bank transfers"],
    cities: ["Addis Ababa", "Dire Dawa", "Mekelle", "Bahir Dar", "Hawassa", "Adama"],
    note: "Ethiopian retailers and wholesalers need a POS that keeps billing through connectivity drops and records telebirr payments.",
    focus: trade,
  },
  {
    slug: "zambia",
    name: "Zambia",
    continent: "Africa",
    code: "ZM",
    currency: "ZMW",
    currencySymbol: "K",
    tax: "VAT",
    payments: ["MTN MoMo", "Airtel Money", "cards"],
    cities: ["Lusaka", "Kitwe", "Ndola", "Livingstone", "Kabwe"],
    note: "Zambian shops and hardware stores handle mobile money, bulk buyers and power interruptions every week.",
    focus: ["supermarket-grocery", "hardware-store", "wholesale-distribution"],
  },
  {
    slug: "rwanda",
    name: "Rwanda",
    continent: "Africa",
    code: "RW",
    currency: "RWF",
    currencySymbol: "FRw",
    tax: "VAT",
    payments: ["MTN MoMo", "Airtel Money"],
    cities: ["Kigali", "Musanze", "Huye", "Rubavu"],
    note: "Rwandan supermarkets and pharmacies need clear VAT reporting and mobile-money reconciliation.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile"],
  },
  {
    slug: "mauritius",
    name: "Mauritius",
    continent: "Africa",
    code: "MU",
    currency: "MUR",
    currencySymbol: "Rs",
    tax: "VAT",
    payments: ["Juice", "my.t money", "cards"],
    cities: ["Port Louis", "Curepipe", "Quatre Bornes", "Vacoas", "Rose Hill"],
    note: "Mauritian boutiques, pharmacies and supermarkets serve both locals and tourists and need clean VAT records.",
    focus: ["supermarket-grocery", "pharmacy", "clothing-textile"],
  },

  // ───────────── Europe ─────────────
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    continent: "Europe",
    code: "GB",
    currency: "GBP",
    currencySymbol: "£",
    tax: "VAT",
    payments: ["contactless cards", "Apple Pay", "Google Pay"],
    cities: ["London", "Birmingham", "Manchester", "Leeds", "Glasgow", "Liverpool", "Bristol"],
    note: "UK convenience stores, off-licences and independent pharmacies need fast card checkout, VAT reports and one-off licensing instead of monthly fees.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile", "clothing-textile"],
    regionLabel: "nation",
    regions: r([
      ["England", ["London", "Birmingham", "Manchester", "Leeds", "Liverpool", "Leicester", "Bristol"]],
      ["Scotland", ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness"]],
      ["Wales", ["Cardiff", "Swansea", "Newport", "Wrexham"]],
      ["Northern Ireland", ["Belfast", "Derry", "Lisburn", "Newry"]],
    ]),
  },
  {
    slug: "ireland",
    name: "Ireland",
    continent: "Europe",
    code: "IE",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT",
    payments: ["contactless cards", "Apple Pay", "Google Pay"],
    cities: ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
    note: "Irish convenience shops, pharmacies and hardware stores want a straightforward POS with VAT reports and no monthly subscription.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store"],
  },
  {
    slug: "germany",
    name: "Germany",
    continent: "Europe",
    code: "DE",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT (MwSt.)",
    payments: ["girocard", "cards", "cash"],
    cities: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf"],
    note: "Many German shops still take a lot of cash, so shift cash counts and till control matter as much as card payments.",
    focus: ["supermarket-grocery", "bakery-cafe", "electronics-mobile"],
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    continent: "Europe",
    code: "NL",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT (BTW)",
    payments: ["debit cards", "contactless", "iDEAL transfers"],
    cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
    note: "Dutch toko shops, groceries and phone shops need quick card checkout and accurate BTW reporting.",
    focus: ["supermarket-grocery", "electronics-mobile", "bakery-cafe"],
  },
  {
    slug: "france",
    name: "France",
    continent: "Europe",
    code: "FR",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT (TVA)",
    payments: ["Carte Bancaire", "contactless", "cash"],
    cities: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Lille"],
    note: "French épiceries, bakeries and independent shops need fast billing and clear TVA summaries.",
    focus: ["supermarket-grocery", "bakery-cafe", "cosmetics-beauty"],
  },
  {
    slug: "italy",
    name: "Italy",
    continent: "Europe",
    code: "IT",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT (IVA)",
    payments: ["cards", "contactless", "cash"],
    cities: ["Rome", "Milan", "Naples", "Turin", "Bologna", "Florence"],
    note: "Italian alimentari, bars and independent shops need a simple counter POS with stock control and IVA reports.",
    focus: ["supermarket-grocery", "bakery-cafe", "clothing-textile"],
  },
  {
    slug: "spain",
    name: "Spain",
    continent: "Europe",
    code: "ES",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT (IVA)",
    payments: ["cards", "Bizum", "cash"],
    cities: ["Madrid", "Barcelona", "Valencia", "Seville", "Málaga", "Bilbao"],
    note: "Spanish mini markets, bazars and phone shops need quick billing, Bizum payment records and IVA summaries.",
    focus: ["supermarket-grocery", "electronics-mobile", "bakery-cafe"],
  },
  {
    slug: "portugal",
    name: "Portugal",
    continent: "Europe",
    code: "PT",
    currency: "EUR",
    currencySymbol: "€",
    tax: "VAT (IVA)",
    payments: ["Multibanco", "MB WAY", "cards"],
    cities: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
    note: "Portuguese mini mercados and shops need fast checkout and MB WAY payment records.",
    focus: ["supermarket-grocery", "bakery-cafe"],
  },

  // ───────────── North America ─────────────
  {
    slug: "united-states",
    name: "United States",
    continent: "North America",
    code: "US",
    currency: "USD",
    currencySymbol: "$",
    tax: "sales tax",
    payments: ["credit and debit cards", "Apple Pay", "Zelle", "checks"],
    cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Dallas", "Miami", "Atlanta"],
    note: "Independent US convenience stores, liquor stores, pharmacies and ethnic groceries want a fast POS without monthly SaaS fees or payment-processor lock-in.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile", "cosmetics-beauty"],
    regionLabel: "state",
    regions: r([
      ["Alabama", ["Birmingham", "Montgomery", "Huntsville", "Mobile"]],
      ["Alaska", ["Anchorage", "Fairbanks", "Juneau"]],
      ["Arizona", ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler"]],
      ["Arkansas", ["Little Rock", "Fayetteville", "Fort Smith", "Jonesboro"]],
      ["California", ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Fresno", "Oakland"]],
      ["Colorado", ["Denver", "Colorado Springs", "Aurora", "Boulder", "Fort Collins"]],
      ["Connecticut", ["Hartford", "New Haven", "Stamford", "Bridgeport"]],
      ["Delaware", ["Wilmington", "Dover", "Newark"]],
      ["District of Columbia", ["Washington", "Georgetown", "Capitol Hill"]],
      ["Florida", ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "Tallahassee"]],
      ["Georgia", ["Atlanta", "Savannah", "Augusta", "Columbus", "Macon"]],
      ["Hawaii", ["Honolulu", "Hilo", "Kailua", "Kahului"]],
      ["Idaho", ["Boise", "Nampa", "Idaho Falls", "Pocatello"]],
      ["Illinois", ["Chicago", "Aurora", "Naperville", "Springfield", "Rockford"]],
      ["Indiana", ["Indianapolis", "Fort Wayne", "Evansville", "South Bend"]],
      ["Iowa", ["Des Moines", "Cedar Rapids", "Davenport", "Iowa City"]],
      ["Kansas", ["Wichita", "Overland Park", "Kansas City", "Topeka"]],
      ["Kentucky", ["Louisville", "Lexington", "Bowling Green", "Owensboro"]],
      ["Louisiana", ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette"]],
      ["Maine", ["Portland", "Bangor", "Lewiston", "Augusta"]],
      ["Maryland", ["Baltimore", "Silver Spring", "Rockville", "Annapolis", "Frederick"]],
      ["Massachusetts", ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"]],
      ["Michigan", ["Detroit", "Grand Rapids", "Dearborn", "Lansing", "Ann Arbor"]],
      ["Minnesota", ["Minneapolis", "Saint Paul", "Rochester", "Duluth"]],
      ["Mississippi", ["Jackson", "Gulfport", "Hattiesburg", "Biloxi"]],
      ["Missouri", ["Kansas City", "St. Louis", "Springfield", "Columbia"]],
      ["Montana", ["Billings", "Missoula", "Bozeman", "Great Falls"]],
      ["Nebraska", ["Omaha", "Lincoln", "Bellevue", "Grand Island"]],
      ["Nevada", ["Las Vegas", "Henderson", "Reno", "North Las Vegas"]],
      ["New Hampshire", ["Manchester", "Nashua", "Concord", "Portsmouth"]],
      ["New Jersey", ["Newark", "Jersey City", "Paterson", "Edison", "Trenton"]],
      ["New Mexico", ["Albuquerque", "Las Cruces", "Santa Fe", "Rio Rancho"]],
      ["New York", ["New York City", "Brooklyn", "Queens", "Buffalo", "Rochester", "Albany"]],
      ["North Carolina", ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"]],
      ["North Dakota", ["Fargo", "Bismarck", "Grand Forks", "Minot"]],
      ["Ohio", ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"]],
      ["Oklahoma", ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow"]],
      ["Oregon", ["Portland", "Salem", "Eugene", "Beaverton"]],
      ["Pennsylvania", ["Philadelphia", "Pittsburgh", "Allentown", "Harrisburg", "Erie"]],
      ["Rhode Island", ["Providence", "Warwick", "Cranston", "Pawtucket"]],
      ["South Carolina", ["Columbia", "Charleston", "Greenville", "Myrtle Beach"]],
      ["South Dakota", ["Sioux Falls", "Rapid City", "Aberdeen"]],
      ["Tennessee", ["Nashville", "Memphis", "Knoxville", "Chattanooga"]],
      ["Texas", ["Houston", "Dallas", "San Antonio", "Austin", "Fort Worth", "El Paso", "Plano"]],
      ["Utah", ["Salt Lake City", "Provo", "West Valley City", "Ogden"]],
      ["Vermont", ["Burlington", "Montpelier", "Rutland"]],
      ["Virginia", ["Virginia Beach", "Richmond", "Arlington", "Norfolk", "Alexandria"]],
      ["Washington", ["Seattle", "Spokane", "Tacoma", "Bellevue", "Vancouver"]],
      ["West Virginia", ["Charleston", "Huntington", "Morgantown"]],
      ["Wisconsin", ["Milwaukee", "Madison", "Green Bay", "Kenosha"]],
      ["Wyoming", ["Cheyenne", "Casper", "Laramie"]],
    ]),
  },
  {
    slug: "canada",
    name: "Canada",
    continent: "North America",
    code: "CA",
    currency: "CAD",
    currencySymbol: "$",
    tax: "GST/HST and PST",
    payments: ["Interac debit", "credit cards", "Interac e-Transfer"],
    cities: ["Toronto", "Vancouver", "Montreal", "Calgary", "Edmonton", "Ottawa", "Mississauga"],
    note: "Canadian convenience stores, ethnic grocers and pharmacies need GST/HST-ready reporting and a POS they own outright instead of renting monthly.",
    focus: ["supermarket-grocery", "pharmacy", "electronics-mobile", "clothing-textile"],
    regionLabel: "province",
    regions: r([
      ["Ontario", ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London"]],
      ["British Columbia", ["Vancouver", "Surrey", "Burnaby", "Richmond", "Victoria"]],
      ["Quebec", ["Montreal", "Quebec City", "Laval", "Gatineau"]],
      ["Alberta", ["Calgary", "Edmonton", "Red Deer", "Lethbridge"]],
      ["Manitoba", ["Winnipeg", "Brandon", "Steinbach"]],
      ["Saskatchewan", ["Saskatoon", "Regina", "Prince Albert"]],
      ["Nova Scotia", ["Halifax", "Dartmouth", "Sydney"]],
      ["New Brunswick", ["Moncton", "Saint John", "Fredericton"]],
      ["Newfoundland and Labrador", ["St. John's", "Mount Pearl", "Corner Brook"]],
      ["Prince Edward Island", ["Charlottetown", "Summerside"]],
      ["Northwest Territories", ["Yellowknife", "Hay River"]],
      ["Yukon", ["Whitehorse", "Dawson City"]],
      ["Nunavut", ["Iqaluit", "Rankin Inlet"]],
    ]),
  },
  {
    slug: "mexico",
    name: "Mexico",
    continent: "North America",
    code: "MX",
    currency: "MXN",
    currencySymbol: "$",
    tax: "IVA",
    payments: ["SPEI transfers", "cards", "CoDi"],
    cities: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Cancún"],
    note: "Mexican abarrotes, farmacias and ferreterías need fast billing, IVA reporting and credit (fiado) control.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store"],
  },

  // ───────────── Latin America & Caribbean ─────────────
  {
    slug: "brazil",
    name: "Brazil",
    continent: "Latin America & Caribbean",
    code: "BR",
    currency: "BRL",
    currencySymbol: "R$",
    tax: "ICMS and other sales taxes",
    payments: ["Pix", "cards", "boleto"],
    cities: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte"],
    note: "Brazilian mercadinhos and farmácias take Pix on most sales and need every payment matched to the right bill.",
    focus: ["supermarket-grocery", "pharmacy", "clothing-textile"],
  },
  {
    slug: "colombia",
    name: "Colombia",
    continent: "Latin America & Caribbean",
    code: "CO",
    currency: "COP",
    currencySymbol: "$",
    tax: "IVA",
    payments: ["Nequi", "Daviplata", "cards"],
    cities: ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
    note: "Colombian tiendas, droguerías and ferreterías need quick billing and Nequi payment records.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store"],
  },
  {
    slug: "jamaica",
    name: "Jamaica",
    continent: "Latin America & Caribbean",
    code: "JM",
    currency: "JMD",
    currencySymbol: "J$",
    tax: "GCT",
    payments: ["cards", "bank transfers", "Lynk"],
    cities: ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "Mandeville"],
    note: "Jamaican wholesales, pharmacies and hardware stores need GCT-ready reports and billing that survives outages.",
    focus: ["wholesale-distribution", "pharmacy", "hardware-store"],
  },
  {
    slug: "trinidad-and-tobago",
    name: "Trinidad and Tobago",
    continent: "Latin America & Caribbean",
    code: "TT",
    currency: "TTD",
    currencySymbol: "TT$",
    tax: "VAT",
    payments: ["Linx debit", "cards"],
    cities: ["Port of Spain", "San Fernando", "Chaguanas", "Arima", "Scarborough"],
    note: "Trinidadian groceries, pharmacies and hardware stores need VAT reports and fast Linx card checkout.",
    focus: ["supermarket-grocery", "pharmacy", "hardware-store"],
  },
  {
    slug: "guyana",
    name: "Guyana",
    continent: "Latin America & Caribbean",
    code: "GY",
    currency: "GYD",
    currencySymbol: "G$",
    tax: "VAT",
    payments: ["MMG", "cards"],
    cities: ["Georgetown", "Linden", "New Amsterdam", "Bartica"],
    note: "Guyana's fast-growing retail sector needs stock control, credit tracking and VAT-ready billing.",
    focus: ["supermarket-grocery", "hardware-store", "wholesale-distribution"],
  },

  // ───────────── Oceania ─────────────
  {
    slug: "australia",
    name: "Australia",
    continent: "Oceania",
    code: "AU",
    currency: "AUD",
    currencySymbol: "$",
    tax: "GST",
    payments: ["EFTPOS", "tap-and-go cards", "PayID"],
    cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Gold Coast"],
    note: "Australian convenience stores, Asian and Indian grocers and pharmacies want a GST-ready POS with no monthly subscription.",
    focus: ["supermarket-grocery", "pharmacy", "bakery-cafe", "electronics-mobile"],
    regionLabel: "state",
    regions: r([
      ["New South Wales", ["Sydney", "Parramatta", "Newcastle", "Wollongong", "Blacktown"]],
      ["Victoria", ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Dandenong"]],
      ["Queensland", ["Brisbane", "Gold Coast", "Cairns", "Townsville", "Toowoomba"]],
      ["Western Australia", ["Perth", "Fremantle", "Mandurah", "Bunbury"]],
      ["South Australia", ["Adelaide", "Mount Gambier", "Whyalla"]],
      ["Tasmania", ["Hobart", "Launceston", "Devonport"]],
      ["Australian Capital Territory", ["Canberra", "Belconnen", "Tuggeranong"]],
      ["Northern Territory", ["Darwin", "Alice Springs", "Palmerston"]],
    ]),
  },
  {
    slug: "new-zealand",
    name: "New Zealand",
    continent: "Oceania",
    code: "NZ",
    currency: "NZD",
    currencySymbol: "$",
    tax: "GST",
    payments: ["EFTPOS", "contactless cards"],
    cities: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin"],
    note: "Kiwi dairies, superettes and pharmacies need fast EFTPOS checkout and GST-ready reports.",
    focus: ["supermarket-grocery", "pharmacy", "bakery-cafe"],
  },
  {
    slug: "fiji",
    name: "Fiji",
    continent: "Oceania",
    code: "FJ",
    currency: "FJD",
    currencySymbol: "FJ$",
    tax: "VAT",
    payments: ["M-PAiSA", "MyCash", "cards"],
    cities: ["Suva", "Lautoka", "Nadi", "Labasa", "Ba"],
    note: "Fijian supermarkets and hardware shops need offline billing and mobile-wallet payment records.",
    focus: ["supermarket-grocery", "hardware-store", "wholesale-distribution"],
  },
];

export const continents = Array.from(new Set(countries.map((c) => c.continent)));

export const getCountry = (slug: string) => countries.find((c) => c.slug === slug);

export const getRegion = (country: Country, slug: string) => country.regions?.find((r) => r.slug === slug);

export const allRegionParams = () =>
  countries.flatMap((c) => (c.regions ?? []).map((reg) => ({ country: c.slug, region: reg.slug })));
