export type Location = {
  slug: string;
  name: string;
  district: string;
  province: string;
  /** Nearby towns also covered, used in copy and keywords. */
  nearby: string[];
  /** One sentence about the local trade that the page opens with. */
  note: string;
  /** Industry slugs most common locally (see lib/industries.ts). */
  focus: string[];
};

export const locations: Location[] = [
  {
    slug: "colombo",
    name: "Colombo",
    district: "Colombo",
    province: "Western",
    nearby: ["Pettah", "Wellawatte", "Bambalapitiya", "Borella", "Maradana", "Kotahena", "Kollupitiya"],
    note: "From Pettah wholesalers to supermarkets in Wellawatte and pharmacies along Galle Road, Colombo's counters handle some of the busiest queues in the country, and our team is based right here.",
    focus: ["supermarket-grocery", "pharmacy", "wholesale-distribution", "clothing-textile"],
  },
  {
    slug: "dehiwala-mount-lavinia",
    name: "Dehiwala-Mount Lavinia",
    district: "Colombo",
    province: "Western",
    nearby: ["Dehiwala", "Mount Lavinia", "Ratmalana", "Kalubowila", "Attidiya"],
    note: "Dense residential streets mean neighbourhood groceries, bakeries and pharmacies that serve the same families every day.",
    focus: ["supermarket-grocery", "bakery-cafe", "pharmacy"],
  },
  {
    slug: "sri-jayawardenepura-kotte",
    name: "Sri Jayawardenepura Kotte",
    district: "Colombo",
    province: "Western",
    nearby: ["Rajagiriya", "Nugegoda", "Battaramulla", "Nawala", "Maharagama"],
    note: "Nugegoda, Rajagiriya and Battaramulla are packed with retail streets where fast billing and tight stock control decide margins.",
    focus: ["supermarket-grocery", "electronics-mobile", "cosmetics-beauty"],
  },
  {
    slug: "moratuwa",
    name: "Moratuwa",
    district: "Colombo",
    province: "Western",
    nearby: ["Katubedda", "Rawathawatte", "Angulana", "Egoda Uyana"],
    note: "Known for furniture and hardware trade, Moratuwa's shops sell by piece, metre and box, often to trade customers on credit.",
    focus: ["hardware-store", "supermarket-grocery", "wholesale-distribution"],
  },
  {
    slug: "homagama",
    name: "Homagama",
    district: "Colombo",
    province: "Western",
    nearby: ["Kottawa", "Pannipitiya", "Padukka", "Meegoda", "Godagama"],
    note: "Fast-growing suburbs along the High Level Road have brought new supermarkets, hardware stores and pharmacies to every junction.",
    focus: ["hardware-store", "supermarket-grocery", "pharmacy"],
  },
  {
    slug: "negombo",
    name: "Negombo",
    district: "Gampaha",
    province: "Western",
    nearby: ["Katunayake", "Seeduwa", "Kochchikade", "Wattala", "Ja-Ela"],
    note: "Tourist shops, fish-market suppliers and busy town-centre retailers near the airport all need billing that never stalls.",
    focus: ["supermarket-grocery", "clothing-textile", "bakery-cafe"],
  },
  {
    slug: "gampaha",
    name: "Gampaha",
    district: "Gampaha",
    province: "Western",
    nearby: ["Kiribathgoda", "Kadawatha", "Ja-Ela", "Minuwangoda", "Veyangoda", "Nittambuwa"],
    note: "Kiribathgoda and Kadawatha are among the busiest retail strips in the country, full of textile, grocery and electronics shops.",
    focus: ["clothing-textile", "supermarket-grocery", "electronics-mobile"],
  },
  {
    slug: "kalutara",
    name: "Kalutara",
    district: "Kalutara",
    province: "Western",
    nearby: ["Panadura", "Horana", "Beruwala", "Aluthgama", "Matugama", "Wadduwa"],
    note: "From Panadura's town centre to Horana and Beruwala, Kalutara district shops mix local groceries with tourist trade.",
    focus: ["supermarket-grocery", "hardware-store", "pharmacy"],
  },
  {
    slug: "kandy",
    name: "Kandy",
    district: "Kandy",
    province: "Central",
    nearby: ["Peradeniya", "Katugastota", "Gampola", "Kundasale", "Digana", "Akurana"],
    note: "Kandy town's pharmacies, bookshops and textile stores serve the whole hill country, with sharp peaks around the Esala Perahera season.",
    focus: ["pharmacy", "bookshop-stationery", "clothing-textile", "supermarket-grocery"],
  },
  {
    slug: "matale",
    name: "Matale",
    district: "Matale",
    province: "Central",
    nearby: ["Dambulla", "Galewela", "Ukuwela", "Rattota"],
    note: "Dambulla's wholesale vegetable trade and Matale's spice sellers depend on accurate weight-based billing and credit tracking.",
    focus: ["wholesale-distribution", "supermarket-grocery"],
  },
  {
    slug: "nuwara-eliya",
    name: "Nuwara Eliya",
    district: "Nuwara Eliya",
    province: "Central",
    nearby: ["Hatton", "Talawakele", "Ragala", "Welimada"],
    note: "Seasonal tourist rush in April and estate-town shops make offline billing and simple cash control essential.",
    focus: ["supermarket-grocery", "bakery-cafe"],
  },
  {
    slug: "galle",
    name: "Galle",
    district: "Galle",
    province: "Southern",
    nearby: ["Hikkaduwa", "Ambalangoda", "Karapitiya", "Unawatuna", "Baddegama", "Elpitiya"],
    note: "Galle town's retailers serve both locals and visitors to the Fort and the southern beaches, all year round.",
    focus: ["supermarket-grocery", "pharmacy", "cosmetics-beauty"],
  },
  {
    slug: "matara",
    name: "Matara",
    district: "Matara",
    province: "Southern",
    nearby: ["Weligama", "Akuressa", "Dikwella", "Kamburupitiya", "Hakmana"],
    note: "Matara's busy town centre and growing suburbs have a strong mix of textile, grocery and hardware shops.",
    focus: ["clothing-textile", "hardware-store", "supermarket-grocery"],
  },
  {
    slug: "hambantota",
    name: "Hambantota",
    district: "Hambantota",
    province: "Southern",
    nearby: ["Tangalle", "Tissamaharama", "Ambalantota", "Beliatta"],
    note: "Shops across Tangalle, Tissamaharama and Ambalantota need a POS that runs reliably on local internet and power.",
    focus: ["supermarket-grocery", "hardware-store"],
  },
  {
    slug: "jaffna",
    name: "Jaffna",
    district: "Jaffna",
    province: "Northern",
    nearby: ["Nallur", "Chunnakam", "Point Pedro", "Chavakachcheri", "Kopay", "Manipay"],
    note: "Jaffna's jewellery, textile, pharmacy and wholesale traders around the Grand Bazaar deal in high volumes and trade credit.",
    focus: ["wholesale-distribution", "clothing-textile", "pharmacy", "supermarket-grocery"],
  },
  {
    slug: "vavuniya",
    name: "Vavuniya",
    district: "Vavuniya",
    province: "Northern",
    nearby: ["Cheddikulam", "Omanthai", "Nedunkerny"],
    note: "As the gateway to the North, Vavuniya's wholesalers and retailers supply a wide surrounding area on credit.",
    focus: ["wholesale-distribution", "supermarket-grocery", "hardware-store"],
  },
  {
    slug: "kilinochchi",
    name: "Kilinochchi",
    district: "Kilinochchi",
    province: "Northern",
    nearby: ["Paranthan", "Pallai", "Mullaitivu"],
    note: "Growing town-centre shops in Kilinochchi and Mullaitivu need a POS that keeps billing when connectivity drops.",
    focus: ["supermarket-grocery", "hardware-store"],
  },
  {
    slug: "mannar",
    name: "Mannar",
    district: "Mannar",
    province: "Northern",
    nearby: ["Pesalai", "Madhu", "Murunkan"],
    note: "Mannar's island and mainland shops rely on offline billing and simple stock control across long supply lines.",
    focus: ["supermarket-grocery", "wholesale-distribution"],
  },
  {
    slug: "trincomalee",
    name: "Trincomalee",
    district: "Trincomalee",
    province: "Eastern",
    nearby: ["Kinniya", "Muttur", "Nilaveli", "Kantale"],
    note: "Trincomalee's town, harbour trade and beach tourism create steady demand for fast, reliable counter billing.",
    focus: ["supermarket-grocery", "bakery-cafe", "hardware-store"],
  },
  {
    slug: "batticaloa",
    name: "Batticaloa",
    district: "Batticaloa",
    province: "Eastern",
    nearby: ["Kattankudy", "Eravur", "Valaichchenai", "Kaluwanchikudy"],
    note: "Kattankudy's textile trade and Batticaloa's busy markets need billing that handles festival rushes and discounting.",
    focus: ["clothing-textile", "wholesale-distribution", "supermarket-grocery"],
  },
  {
    slug: "ampara",
    name: "Ampara",
    district: "Ampara",
    province: "Eastern",
    nearby: ["Kalmunai", "Akkaraipattu", "Sainthamaruthu", "Pottuvil", "Dehiattakandiya"],
    note: "From Kalmunai's trading streets to Akkaraipattu, Ampara district retailers deal in groceries, textiles and hardware.",
    focus: ["clothing-textile", "supermarket-grocery", "hardware-store"],
  },
  {
    slug: "kurunegala",
    name: "Kurunegala",
    district: "Kurunegala",
    province: "North Western",
    nearby: ["Kuliyapitiya", "Pannala", "Narammala", "Wariyapola", "Mawathagama", "Nikaweratiya"],
    note: "A major junction town, Kurunegala's wholesalers, hardware shops and supermarkets serve a large farming region.",
    focus: ["wholesale-distribution", "hardware-store", "supermarket-grocery"],
  },
  {
    slug: "puttalam",
    name: "Puttalam",
    district: "Puttalam",
    province: "North Western",
    nearby: ["Chilaw", "Wennappuwa", "Marawila", "Nattandiya", "Anamaduwa"],
    note: "Chilaw, Wennappuwa and Puttalam town shops blend coastal trade with busy grocery and hardware counters.",
    focus: ["supermarket-grocery", "hardware-store"],
  },
  {
    slug: "anuradhapura",
    name: "Anuradhapura",
    district: "Anuradhapura",
    province: "North Central",
    nearby: ["Kekirawa", "Medawachchiya", "Eppawala", "Tambuttegama", "Thalawa"],
    note: "Agricultural supply shops, pharmacies and supermarkets in the new town serve pilgrims and a wide farming community.",
    focus: ["hardware-store", "supermarket-grocery", "pharmacy"],
  },
  {
    slug: "polonnaruwa",
    name: "Polonnaruwa",
    district: "Polonnaruwa",
    province: "North Central",
    nearby: ["Hingurakgoda", "Kaduruwela", "Medirigiriya", "Aralaganwila"],
    note: "Paddy-country towns like Kaduruwela and Hingurakgoda depend on grocery and agri-hardware shops that sell in bulk.",
    focus: ["wholesale-distribution", "hardware-store", "supermarket-grocery"],
  },
  {
    slug: "badulla",
    name: "Badulla",
    district: "Badulla",
    province: "Uva",
    nearby: ["Bandarawela", "Welimada", "Haputale", "Mahiyanganaya", "Passara", "Ella"],
    note: "Badulla and Bandarawela shops serve estate communities and hill-country tourism around Ella and Haputale.",
    focus: ["supermarket-grocery", "pharmacy", "bakery-cafe"],
  },
  {
    slug: "monaragala",
    name: "Monaragala",
    district: "Monaragala",
    province: "Uva",
    nearby: ["Wellawaya", "Buttala", "Bibile", "Siyambalanduwa"],
    note: "Monaragala's rural town centres need a simple, offline POS that a new cashier can learn in a day.",
    focus: ["supermarket-grocery", "hardware-store"],
  },
  {
    slug: "ratnapura",
    name: "Ratnapura",
    district: "Ratnapura",
    province: "Sabaragamuwa",
    nearby: ["Embilipitiya", "Balangoda", "Pelmadulla", "Eheliyagoda", "Kuruwita"],
    note: "Ratnapura's gem-trade town and Embilipitiya's busy markets need accurate cash control and supplier tracking.",
    focus: ["supermarket-grocery", "hardware-store", "pharmacy"],
  },
  {
    slug: "kegalle",
    name: "Kegalle",
    district: "Kegalle",
    province: "Sabaragamuwa",
    nearby: ["Mawanella", "Warakapola", "Rambukkana", "Ruwanwella", "Yatiyantota"],
    note: "Mawanella and Warakapola sit on the Colombo–Kandy road, where roadside retailers see traffic all day.",
    focus: ["supermarket-grocery", "hardware-store", "bakery-cafe"],
  },
];

export const getLocation = (slug: string) => locations.find((l) => l.slug === slug);

export const provinces = Array.from(new Set(locations.map((l) => l.province)));
